build:
	g++ Computer.cpp Heap.cpp Log.cpp RequestHandler.cpp simulator.cpp -o simulator
clean:
	rm simulator
run:
	./simulator log1.txt 5 > output1.txt
	./simulator log2.txt 15 > output2.txt
	./simulator log3.txt 46 > output3.txt
	./simulator log3.txt 17 > output4.txt